### ISSUE TITLE
칭호 출력버그?

### ISSUE THREAD

**Issue by pic-ture** [Riey/erars#21]
![image](https://user-images.githubusercontent.com/100054967/194692180-3401c1bd-4335-4173-9538-04708e48c818.png)

새로운 칭호를 얻을수있다 뜨는데 정작 무슨칭호인지 보이지않음.

**Comment by Riey** [comment]
어떤 상황에서 얻은 칭호인가요?

**Comment by pic-ture** [comment]
조교가 끝난후 나가기 할때 떴는데 제가 ym을 잘 몰라서 어떤 칭호인진 모르겠습니다.
