### ISSUE TITLE
노예 구매시 튕김현상

### ISSUE THREAD

**Issue by pic-ture** [Riey/erars#3]
https://gitgud.io/riey/eraTHYMKR 여기서 받은 ym으로 했습니다.

ym 이지에 토리코 기본세트(10) 에서 시작하자마자 레이무 구매했는데 튕겼습니다.

로그

INFO [erars] Load config: EraConfig { lang: Korean }
WARN [erars] Unknown csv name _RENAME
INFO [erars] Replace: ReplaceInfo { money_unit: "원", unit_forward: false, start_message: "신사망상중...", sell_item_count: 0, drawline_str: "-", bar_str1: "*", bar_str2: ".", system_menu0: "[0] 最初からはじめる", system_menu1: "[1] ロードしてはじめる", comable_init: 0, stain_init: [0, 0, 2, 1, 8, 0, 0, 0], timeout_message: "時間切れ", explv_init: [0, 1, 4, 20, 50, 200, 400, 700, 1000, 1500, 2000], palamlv_init: [0, 100, 500, 3000, 10000, 30000, 60000, 100000, 150000, 250000, 500000, 1000000, 5000000, 10000000, 50000000], pband_init: 0, relation_init: 0 }
WARN [erars] Unknown csv name MARK
WARN [erars] Unknown csv name JUEL
WARN [erars] Unknown csv name NOWEX
WARN [erars] Unknown csv name GAMEBASE
WARN [erars] Unknown csv name TCVAR
WARN [erars] Unknown csv name VARIABLESIZE
WARN [erars::vm] TODO: fontstyle(0)
WARN [erars::vm] TODO: fontstyle(0)
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] Ignore SP feature
WARN [erars::vm] Ignore SP feature
WARN [erars::vm] Ignore SP feature
WARN [erars::vm] Ignore SP feature
WARN [erars::vm] Ignore SP feature
WARN [erars::vm] Ignore SP feature
WARN [erars::vm] TODO: FONTBOLD
WARN [erars::vm] TODO: FONTREGULAR
WARN [erars::vm] Ignore SP feature
ERROR [erars::vm] VM failed with: Variable out of range 11000
ERROR [erars::vm]     at function SET_CALLNAME@2687 `ERB\SYS\PRINT_STATE.ERB` [        STR:(COUNT + 11000) = %CSVNAME(COUNT, 0)%]
ERROR [erars::vm]     at function PRINT_RELATION@1125 `ERB\SYS\PRINT_STATE.ERB` [CALL SET_CALLNAME]
ERROR [erars::vm]     at function SHOW_ADDITIONAL_INFO@125 `ERB\SYS\SHOP\SHOP_CHARALIST.ERB` [    CALL PRINT_RELATION, LOCAL:1]
ERROR [erars::vm]     at function CHARA_PROFILE@1580 `ERB\SYS\SHOP\SHOP_CHARALIST.ERB` [    CALL SHOW_ADDITIONAL_INFO]
ERROR [erars::vm]     at function CHARA_MANUAL@12 `ERB\SYS\SHOP\SHOP_CHARALIST.ERB` [CALL CHARA_PROFILE]
ERROR [erars::vm]     at function CHARA_BUY_MAIN@143 `ERB\SYS\SHOP\SHOP_CHARABUY.ERB` [    CALL CHARA_MANUAL]
ERROR [erars::vm]     at function USERSHOP@536 `ERB\SYS\SHOP\SHOP.ERB` [        CALL CHARA_BUY_MAIN]
INFO [erars] Program Terminated

**Comment by Riey** [comment]
variablesize.csv를 읽어야 해결되겠네요
