### ISSUE TITLE
버튼 파싱 오류

### ISSUE THREAD

**Issue by ruby-textark** [Riey/erars#35]
`>[ 9] 2022年10月08日 22:52:52    1일째 낮`
이라는 스트링을

![image](https://user-images.githubusercontent.com/115135804/194711113-de749a20-6088-4f88-9cd6-9d758a091436.png)

하나의 버튼으로 인식하지 못합니다

**Comment by Riey** [comment]
[ 9]랑 뒤에것이 따로 출력됐는데 이런 경우에도 버튼으로 합쳐지는게 맞는건가요?

**Comment by ruby-textark** [comment]
![image](https://user-images.githubusercontent.com/115135804/194712858-c6603320-4b50-4516-adc3-1f761762ebb4.png)

이게 한덩어리라네요
