### ISSUE TITLE
eraTHYMKR 실행 불가능

### ISSUE THREAD

**Issue by ruby-textark** [Riey/erars#49]
새 게임 시작해서 eratohoYM 선택 후 어떤 난이도를 선택해도 실행되지 않습니다.
추가로 100 HELP를 선택하면 작동이 정지합니다.

json flag를 켜든 안 켜든 동일한 문제가 발생합니다.

**Comment by ruby-textark** [comment]
![image](https://user-images.githubusercontent.com/115135804/196331669-29fee452-0b7c-45bc-bf59-8aef88f03a16.png)

여전히 문제가 발생합니다.

ERROR [erars_vm::terminal_vm] VM error occurred: invalid type: map, expected u32
ERROR [erars_vm::terminal_vm] At function START_CONFIGURATION ..\eraTHYMKR\ERB\SYS\CONFIG\CONFIG0.ERB@5

**Comment by Riey** [comment]
![화면 캡처 2022-10-18 130247](https://user-images.githubusercontent.com/14910534/196332778-bd681ecc-faf2-470d-8f12-a003f4be1849.png)

master 브렌치 확인하신거 맞나요?

**Comment by Riey** [comment]
> ![image](https://user-images.githubusercontent.com/115135804/196331669-29fee452-0b7c-45bc-bf59-8aef88f03a16.png)
> 
> 여전히 문제가 발생합니다.
> 
> ERROR [erars_vm::terminal_vm] VM error occurred: invalid type: map, expected u32 ERROR [erars_vm::terminal_vm] At function START_CONFIGURATION ..\eraTHYMKR\ERB\SYS\CONFIG\CONFIG0.ERB@5

아 json에서 문제가 되네요

**Comment by ruby-textark** [comment]
아예 Nightly쪽(https://github.com/Riey/erars/actions/runs/3270124024) 에서 다운받아서 다시 돌려봤는데 안되네요.

혹시 바이트코드 캐싱이라든지 다른 문제가 생길 부분이 있나요?

**Comment by Riey** [comment]
stdio로 돌려도 안되나요?

**Comment by ruby-textark** [comment]
네 stdio도 문제가 있네요

**Comment by Riey** [comment]
nightly에서 stdio.exe 받아서 실행하니까 잘 되는데 이상하네요 --load 안쓰셨죠?

**Comment by Riey** [comment]
아 세이브 문제인거 같네요 지우면 해결될겁니다 에러 좀 잘 보이게 바꿔놓을게요
