### ISSUE TITLE
eraSQN 에러

### ISSUE THREAD

**Issue by pic-ture** [Riey/erars#52]
https://gitgud.io/mosochu/EraSQNK 여기서 받은 sqn입니다.
게임실행시 튕기진 않으나, 아래와 같은 오류가 납니다.

error[E0001]: Compile ERROR
     ┌─ CSV\ITEM.CSV:232:1
     │
 232 │ 401,몽마의비키니
     │ ^^^^^^^^^^^^^^^^ CSV 형식이 잘못됐습니다.
     │
     ┌─ ERB\ABL\ABLUP.ERB:624:3
     │
 624 │         FORCEWAIT
     │         ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\EVENT\EVENT_NINSHIN.ERB:157:4
     │
 157 │             FORCEWAIT
     │             ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\EVENT\EVENT_TRAVEL_NTR.ERB:212:6
     │
 212 │                     NPC_NAME =
     │                     ^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '(' at:
Alt at:
in section 'single_expr', at:

     │
     ┌─ ERB\EVENT\EXPLORER_EVENT.ERB:707:1
     │
 707 │ FORCEWAIT
     │ ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\EVENT\VIDEONAME.ERB:21:4
     │
  21 │             V_TITLE = %V_TITLE% 아나타의%조사처리(TEXTS("匂い"),"가")% 난다…♪
     │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '(' at: %V_TITLE% 아나타의%조사처리(TEXTS("匂い"),"가")% 난다…♪
Alt at: %V_TITLE% 아나타의%조사처리(TEXTS("匂い"),"가")% 난다…♪
in section 'single_expr', at: %V_TITLE% 아나타의%조사처리(TEXTS("匂い"),"가")% 난다…♪

     │
     ┌─ ERB\EVENT_K\DEVENT_K25_2.ERB:2268:5
     │
2268 │                 FORCEWAIT
     │                 ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\EVENT_K\EVENT_K22_2_829.ERB:6933:4
     │
6933 │             FORCEWAIT
     │             ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\EVENT_K\EVENT_K95.ERB:133:3
     │
 133 │         TALENT:유아／유아퇴행 = 1
     │         ^^^^^^^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at: ／유아퇴행 = 1
in section 'AssignOp', at: ／유아퇴행 = 1

     │
     ┌─ ERB\SHOP\PRINT_LIST.ERB:446:2
     │
 446 │     PRINTFORML -%조사처리(CALLNAME:TOINT(CHOICES:1),"이")% 기억하고 있는 아르카나의 목록-
     │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '(' at: 조사처리(CALLNAME:TOINT(CHOICES:1),"이")% 기억하고 있는 아르카나의 목록-
Alt at: 조사처리(CALLNAME:TOINT(CHOICES:1),"이")% 기억하고 있는 아르카나의 목록-
in section 'single_expr', at: 조사처리(CALLNAME:TOINT(CHOICES:1),"이")% 기억하고 있는 아르카나의 목록-

     │
     ┌─ ERB\SHOP\SAMONTRBL.ERB:563:1
     │
 563 │ ELSEIF GETBIT(P, 0) || (RAND:4 == 0 && TALENT:처녀 == 0 && TALENT:MASTER:소환천재（天才） == 0)
     │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected ')' at: （天才） == 0)
Alt at: (RAND:4 == 0 && TALENT:처녀 == 0 && TALENT:MASTER:소환천재（天才） == 0)
in section 'single_expr', at: (RAND:4 == 0 && TALENT:처녀 == 0 && TALENT:MASTER:소환천재（天才） == 0)

     │
     ┌─ ERB\SHOP\SQ_TATTOO.ERB:1110:3
     │
1110 │         TWAIT ANI_SPEED, 0
     │         ^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at: ANI_SPEED, 0
in section 'AssignOp', at: ANI_SPEED, 0

     │
     ┌─ ERB\SHOP\SHOP3.ERB:1106:1
     │
1106 │ ABL_SAMON = 1 + (TALENT:MASTER:소환천재（天才） > 0)*2 + (TALENT:MASTER:소환천재（天災） > 0) + (TALENT:MASTER:수수께끼의매력 > 0) + (TALENT:MASTER:금단의지식 > 0)
     │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected ')' at: （天才） > 0)*2 + (TALENT:MASTER:소환천재（天災） > 0) + (TALENT:MASTER:수수께끼의매력 > 0) + (TALENT:MASTER:금단의지식 > 0)
Alt at: (TALENT:MASTER:소환천재（天才） > 0)*2 + (TALENT:MASTER:소환천재（天災） > 0) + (TALENT:MASTER:수수께끼의매력 > 0) + (TALENT:MASTER:금단의지식 > 0)
in section 'single_expr', at: (TALENT:MASTER:소환천재（天才） > 0)*2 + (TALENT:MASTER:소환천재（天災） > 0) + (TALENT:MASTER:수수께끼의매력 > 0) + (TALENT:MASTER:금단의지식 > 0)

     │
     ┌─ ERB\SYSTEM_NEWGAME.ERB:1091:1
     │
1091 │ ADDCOPYCHARA ARG
     │ ^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at: ARG
in section 'AssignOp', at: ARG

     │
     ┌─ ERB\TRAIN\EVENT_ARCANA.ERB:296:4
     │
 296 │             ADDCOPYCHARA TARGET
     │             ^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at: TARGET
in section 'AssignOp', at: TARGET

     │
     ┌─ ERB\TRAIN\COUNTER_SYSTEM.ERB:1035:2
     │
1035 │     FORCEWAIT
     │     ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\SHOP\SHOP.ERB:1562:2
     │
1562 │     ITEMSALES:☆기교Lv = 1
     │     ^^^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at: :☆기교Lv = 1
in section 'AssignOp', at: :☆기교Lv = 1

     │
     ┌─ ERB\TRAIN\EVENT_SETFLAG.ERB:75:4
     │
  75 │             MEMOS = %TOSTR(BASE:(ARG:2):식별번호)%
     │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '(' at: %TOSTR(BASE:(ARG:2):식별번호)%
Alt at: %TOSTR(BASE:(ARG:2):식별번호)%
in section 'single_expr', at: %TOSTR(BASE:(ARG:2):식별번호)%

     │
     ┌─ ERB\TRAIN\FUNCTION_SQ.ERB:106:3
     │
 106 │         TWAIT 100, 0
     │         ^^^^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at: 100, 0
in section 'AssignOp', at: 100, 0

     │
     ┌─ ERB\TRAIN\EVENT_M.ERB:1355:4
     │
1355 │             FORCEWAIT
     │             ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\TRAIN\TRACHECK.ERB:1015:2
     │
1015 │     FORCEWAIT
     │     ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

     │
     ┌─ ERB\TRAIN\SOURCE.ERB:1446:2
     │
1446 │     FORCEWAIT
     │     ^^^^^^^^^ Expression parsing failed: Parse error:
expected '=' at:
in section 'AssignOp', at:

**Comment by Riey** [comment]
> TALENT:유아／유아퇴행

🤔
