### ISSUE TITLE
eraSQN 몽마스탯 표기오류

### ISSUE THREAD

**Issue by pic-ture** [Riey/erars#61]
eraSQN 에서 몽마의 몇몇 정보가 제대로 표기되지않습니다.
![image](https://user-images.githubusercontent.com/100054967/197343039-379ec794-f4f4-44bb-a5c4-7a643913d750.png)

**Comment by Riey** [comment]
Fixed with [850422e58e6c95ba02ef24d0900399c99d522f7b](https://github.com/Riey/erars/commit/850422e58e6c95ba02ef24d0900399c99d522f7b)
