### ISSUE TITLE
[] string

### ISSUE THREAD

**Issue by ruby-textark** [Riey/erars#73]
EraSQNK
ERB/TRAIN/EVENT_T.ERB에서

3329행 `@NAMES` 를 보면

![image](https://user-images.githubusercontent.com/115135804/198426395-deb60ed9-7932-4558-9e5d-9f547557599f.png)

처럼 []으로 묶어서 넣어버리는데 이게 기존 EE에서는 PRINTFORMLC에서 스트링으로 제대로 나옵니다

ERB/CONFIGURE.ERB에서

831행
`PRINTFORMLC 　[{LCOUNT, 2}] \@GETBIT(TALENT:MASTER:성벽, LCOUNT) ? ○ # － \@ %NAMES("속성", LCOUNT)%`

**Comment by Riey** [comment]
정확히 뭐가 문제인가요

**Comment by Riey** [comment]
[ 0] - [숫자아님] 이게 한 버튼으로 와야하는거 같네요
