### ISSUE TITLE
eraSQN 특정 글자가 제대로 표시되지않음.

### ISSUE THREAD

**Issue by pic-ture** [Riey/erars#79]
SQN에서 몇몇 글자가 제대로 표시되지않습니다.

![image](https://user-images.githubusercontent.com/100054967/198529217-3f79bc38-b791-4b1b-87a6-e0af0f044e80.png)
![image](https://user-images.githubusercontent.com/100054967/198529796-769ffd3e-48a0-40a9-99c5-5fb573a099e9.png)
![image](https://user-images.githubusercontent.com/100054967/198529257-2a8f30aa-b8e8-4a9f-bb97-9cdcc379fc81.png)

![image](https://user-images.githubusercontent.com/100054967/198531407-7bc9eb7d-fb0f-45af-9c2b-4eeda38a3cd6.png)
![image](https://user-images.githubusercontent.com/100054967/198531647-05489b45-6390-4882-a43b-3d120b365d6c.png)

**Comment by Riey** [comment]
stdio는 font fallback 지원하는 터미널을 쓰셔야 합니다
